use awesome;

create table if not exists task_name_remain (id integer not null primary key, create_time datetime not null,
	update_time timestamp not null,
	status integer not null,
	day_1 integer not null,
	day_2 integer not null,
	day_3 integer not null,
	day_4 integer not null,
	day_5 integer not null,
	day_6 integer not null,
	day_7 integer not null,
	day_8 integer not null,
	day_9 integer not null,
	day_10 integer not null,
	day_11 integer not null,
	day_12 integer not null,
	day_13 integer not null,
	day_14 integer not null,
	day_15 integer not null,
	day_16 integer not null,
	day_17 integer not null,
	day_18 integer not null,
	day_19 integer not null,
	day_20 integer not null,
	day_21 integer not null,
	day_22 integer not null,
	day_23 integer not null,
	day_24 integer not null,
	day_25 integer not null,
	day_26 integer not null,
	day_27 integer not null,
	day_28 integer not null,
	day_29 integer not null,
	day_30 integer not null
) engine=innodb default charset=utf8;